;;; boss-theme.el -*- lexical-binding: t; -*-

(require 'doom-themes)

(defgroup boss-theme nil
  "My custom theme for Doom Emacs."
  :group 'doom-themes)

(def-doom-theme boss
  "A high-contrast theme based on the Boss palette."
  :background-mode 'dark

  ;; --- THE PALETTE ---
  ;; name         default     256       16
  ((bg          '("#000000" nil       nil            ))
   (bg-alt      '("#181E24" nil       nil            ))
   (base0       '("#10151C" "black"   "black"        ))
   (base1       '("#171D22" "#111122" "brightblack"  ))
   (base2       '("#20282F" "#222222" "brightblack"  ))
   (base3       '("#28323B" "#223333" "brightblack"  ))
   (base4       '("#384551" "#334455" "brightblack"  ))
   (base5       '("#56697A" "#556677" "brightblack"  ))
   (base6       '("#688094" "#668899" "brightblack"  ))
   (base7       '("#7FA0B7" "#77AABB" "brightblack"  ))
   (base8       '("#9CAABB" "#99AABB" "white"        ))
   (fg-alt      '("#728CA0" "#7788AA" "brightwhite"  ))
   (fg          '("#C6C6C6" "#AABBCC" "white"        ))

   (grey        '("#41505E" "#ff6655" "red"          ))          ; city-lights
   (red         '("#ff7b72" "#ff6655" "red"          ))
   (orange      '("#ffa198" "#dd8844" "brightred"    ))
   (green       '("#3fb950" "#44bb55" "green"        ))
   (teal        '("#56d364" "#55DD66" "brightgreen"  ))
   (yellow      '("#f1d4a8" "#FFDDAA" "yellow"       ))
   (blue        '("#a5d6ff" "#AADDFF" "brightblue"   ))
   (bright-blue '("#58a6ff" "#5599FF" "blue"         ))
   (dark-blue   '("#388bfd" "#3388FF" "blue"         ))
   (magenta     '("#d2a8ff" "#DD99FF" "magenta"      ))
   (violet      '("#8957e5" "#8855EE" "brightmagenta"))
   (cyan        '("#79c0ff" "#77CCFF" "brightcyan"   ))
   (dark-cyan   '("#1f6feb" "#1166EE" "cyan"         ))

   ;; face categories -- required for all themes
   (highlight              blue        )
   (vertical-bar           base2       )
   (selection              dark-blue   )
   (builtin                bright-blue )
   (comments               base6       )
   (doc-comments           base7       )
   (constants              cyan        )
   (functions              magenta     )
   (keywords               red         )
   (methods                magenta     )
   (operators              cyan        )
   (type                   yellow      )
   (strings                blue        )
   (variables              fg          )
   (numbers                cyan        )
   (region                 base3       )
   (error                  red         )
   (warning                yellow      )
   (success                green       )
   (vc-modified            blue        )
   (vc-added               green       )
   (vc-deleted             red         )

   ;; Modeline
   (modeline-fg            fg          )
   (modeline-fg-alt        base5       )
   (modeline-bg            base3       )
   (modeline-bg-inactive   base1       )
   (modeline-bg-active     base3       ))

  ;; 2. FACE OVERRIDES
  ;; SPC : list-faces-display
  ((header-line :background bg :box nil :inherit nil) ;; for terminal tabs
   (minibuffer-prompt :foreground blue)
   (link :foreground blue :weight 'bold :underline t)
   (link-visited :foreground blue :weight 'normal :underline t)
   (vertical-border :foreground base5)
   (trailing-whitespace :foreground teal :underline t)
   (hl-line :background base3)
   (line-number :background bg-alt :foreground base5)
   (line-number-current-line :background bg-alt :foreground base5)
   (isearch :background yellow :foreground bg)
   (lazy-highlight :box `(:line-width -1 :color ,yellow))
   (evil-ex-search :box `(:line-width -1 :color ,yellow))
   (evil-ex-lazy-highlight :box `(:line-width -1 :color ,yellow))
   (mode-line :background base4)
   (mode-line-inactive :background bg)
   (doom-modeline-bar-active :background blue)
   (doom-modeline-evil-insert-state :foreground bright-blue)
   ;; Which-key (leader menu)
   (which-key-key-face :foreground red)
   (which-key-command-description-face :foreground cyan)
   (which-key-group-description-face :foreground dark-blue)
   (which-key-special-key-face :foreground fg)
   ;; Marginalia (vertico file annotations)
   (marginalia-size :foreground green)
   (marginalia-date :foreground fg)
   (marginalia-file-priv-dir :foreground blue)
   (marginalia-file-priv-read :foreground magenta)
   (marginalia-file-priv-write :foreground orange)
   (marginalia-file-priv-exec :foreground yellow)
   ;; Magit / Diff
   (magit-diff-added :foreground green :background base1)
   (magit-diff-added-highlight :foreground green :background base2)
   (magit-diff-removed :foreground red :background base1)
   (magit-diff-removed-highlight :foreground red :background base2)
   (magit-diff-context :foreground base5)
   (magit-diff-context-highlight :background base1)
   (magit-diff-hunk-heading :foreground base7 :background base2)
   (magit-diff-hunk-heading-highlight :foreground fg :background base3)
   (magit-diff-lines-heading :foreground fg :background base3)
   (magit-diff-lines-boundary :foreground fg :background base2)
   (magit-diff-file-heading :foreground blue :weight 'bold)
   (magit-diff-file-heading-highlight :background base2 :weight 'bold)
   (magit-diff-file-heading-selection :background base3 :weight 'bold)
   (magit-header-line :foreground magenta :background bg)
   (magit-diff-revision-summary :foreground cyan :background base2)
   (magit-diff-revision-summary-highlight :foreground cyan :background base3)
   (magit-filename :foreground blue)
   (magit-section-heading :foreground cyan :weight 'bold)
   (magit-section-highlight :background base1)
   (magit-blame-heading :foreground fg :background base3)
   (magit-blame-date :foreground yellow :background base3)
   (magit-blame-name :foreground blue :background base3)
   (magit-blame-summary :foreground fg :background base3)
   (magit-blame-hash :foreground base5 :background base3)
   (magit-blame-margin :background base3)
   (magit-section-heading-selection :foreground fg :background region)
   (magit-branch-remote :foreground yellow)
   (magit-branch-remote-head :foreground yellow :box t)
   (magit-hash :foreground base7)
   (magit-log-author :foreground orange)
   (magit-log-date :foreground base5)
   (diff-added :foreground green :background base1)
   (diff-removed :foreground red :background base1)
   (diff-refine-added :foreground green :background base2)
   (diff-refine-removed :foreground red :background base2)
   ;; Merge conflicts (smerge)
   (smerge-upper :background "#4d000d")
   (smerge-lower :background "#1f3f26")
   (smerge-markers :background bg :extend t)
   ;; Vertico (completion)
   (vertico-current :background base3)
   (corfu-current :background base3)
   ;; Org mode
   (org-table :foreground fg)
   (org-verbatim :foreground base7 :background base1)
   (org-code :foreground base7 :background base1)
   ;; Fill column indicator
   (fill-column-indicator :foreground base4)
   ;; Markdown
   (markdown-code-face :background base1 :extend t)
   (markdown-italic-face :foreground fg :slant 'italic)
   (markdown-bold-face :foreground fg :weight 'bold)
   ;; Transient (magit menu)
   (transient-heading :foreground blue)
   (transient-key-stack :foreground orange)
   (transient-key-exit :foreground cyan)
   ;; Git commit message
   (git-commit-comment-action :foreground orange)
   (git-commit-comment-file :foreground fg)
   (git-commit-comment-heading :foreground base7)
   ;; Dired (diredfl)
   (diredfl-dir-priv :foreground blue)
   (diredfl-read-priv :foreground magenta)
   (diredfl-write-priv :foreground orange)
   (diredfl-exec-priv :foreground yellow)
   (diredfl-no-priv :foreground base5)
   (diredfl-number :foreground green)
   (dired-perm-write :foreground orange)
   ;; Nerd icons
   (nerd-icons-purple :foreground bright-blue)
   (nerd-icons-purple-alt :foreground bright-blue)
   ;; Treemacs
   (treemacs-git-modified-face :foreground blue)
   (treemacs-git-untracked-face :foreground base7)
   (treemacs-git-added-face :foreground green)
   (treemacs-git-renamed-face :foreground blue)
   (treemacs-git-conflict-face :foreground red)
   (treemacs-root-face :foreground blue :weight 'bold :height 1.1)
   ;; Tab bar (top bar)
   (tab-bar :background bg-alt :foreground base5)
   (tab-bar-tab :background bg-alt :foreground fg)
   (tab-bar-tab-inactive :background bg-alt :foreground base5)
   ;; Tree-sitter / Emacs 29+ font-lock faces
   (font-lock-function-call-face :foreground magenta)
   (font-lock-property-use-face :foreground fg)
   (font-lock-number-face :foreground cyan)
   (font-lock-escape-face :foreground orange)
   (font-lock-operator-face :foreground cyan)
   (font-lock-bracket-face :foreground base7)
   ;; Xref / Consult (g r references)
   (xref-file-header :foreground blue :background base3)
   (xref-line-number :foreground base5)
   (xref-match :foreground yellow)
   (consult-file :foreground blue)
   (consult-line-number :foreground base5)
   (consult-highlight-match :foreground yellow)
   (consult-preview-match :background yellow :foreground bg)
   (consult-preview-line :background base3)
   ;; Flycheck popup
   (popup-tip-face :foreground orange :background bg)
   ;; Deadgrep
   (deadgrep-filename-face :foreground blue :weight 'bold :underline nil)
   (deadgrep-meta-face :foreground base7)
   (deadgrep-match-face :inherit 'lazy-highlight)))

(doom-themes-set-faces 'boss)
(provide-theme 'boss)
(provide 'boss-theme)
;;; boss-theme.el ends here
